on:
  # Manual run with parameter for what to do
  workflow_dispatch:
    inputs:
      command:
        required: false
        type: choice
        options:
        - --delete
        - --seed-all
  # Automatic run when this is first created from a template
  push:
    branches:
      - main
      
jobs:
  seed_issues:
    runs-on: ubuntu-latest
    steps:
    - run: ls; ./.github/scripts/prepare-lab-env.sh $OPTION
      env:
        OPTION: ${{ inputs.command }}
